"""empty message

Revision ID: 1a82930e5833
Revises: 6615c23de93d
Create Date: 2023-10-02 19:37:11.005327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a82930e5833'
down_revision = '6615c23de93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_donations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_donations', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('user_donation')
    # ### end Alembic commands ###
